        // 생물 도감 (스페인/스페인어권 테마 + 정체불명 몬스터). rarity: common/rare/epic/legendary
        const CREATURES = [
            // ===== common (일반) =====
            { id: "chick", emoji: "🐤", name: "pollito (병아리)", rarity: "common", desc: "갓 태어난 노란 병아리예요!" },
            { id: "cat", emoji: "🐱", name: "gato (고양이)", rarity: "common", desc: "늘어지게 낮잠을 좋아해요." },
            { id: "dog", emoji: "🐶", name: "perro (개)", rarity: "common", desc: "충직한 친구예요." },
            { id: "frog", emoji: "🐸", name: "rana (개구리)", rarity: "common", desc: "웅덩이에서 폴짝!" },
            { id: "snail", emoji: "🐌", name: "caracol (달팽이)", rarity: "common", desc: "느리지만 꾸준해요." },
            { id: "bee", emoji: "🐝", name: "abeja (벌)", rarity: "common", desc: "부지런한 일꾼이에요." },
            { id: "mouse", emoji: "🐭", name: "ratón (생쥐)", rarity: "common", desc: "작지만 재빨라요." },
            { id: "rabbit", emoji: "🐰", name: "conejo (토끼)", rarity: "common", desc: "깡충깡충 뛰어다녀요." },
            { id: "chicken", emoji: "🐔", name: "gallina (암탉)", rarity: "common", desc: "알을 낳는 엄마예요." },
            { id: "pig", emoji: "🐷", name: "cerdo (돼지)", rarity: "common", desc: "하몽의 주인공이에요." },
            { id: "duck", emoji: "🦆", name: "pato (오리)", rarity: "common", desc: "물에서 둥둥 떠다녀요." },
            { id: "fish", emoji: "🐟", name: "pez (물고기)", rarity: "common", desc: "바닷속을 헤엄쳐요." },
            { id: "cow", emoji: "🐮", name: "vaca (소)", rarity: "common", desc: "음메- 우유를 줘요." },
            { id: "sheep", emoji: "🐑", name: "oveja (양)", rarity: "common", desc: "포근한 털을 가졌어요." },
            { id: "goat", emoji: "🐐", name: "cabra (염소)", rarity: "common", desc: "산을 잘 타요." },
            { id: "hen", emoji: "🐓", name: "gallo (수탉)", rarity: "common", desc: "아침을 알려요." },
            { id: "turkey", emoji: "🦃", name: "pavo (칠면조)", rarity: "common", desc: "크리스마스의 주인공!" },
            { id: "hamster", emoji: "🐹", name: "hámster (햄스터)", rarity: "common", desc: "볼주머니가 빵빵해요." },
            { id: "ant", emoji: "🐜", name: "hormiga (개미)", rarity: "common", desc: "작지만 힘이 세요." },
            { id: "ladybug", emoji: "🐞", name: "mariquita (무당벌레)", rarity: "common", desc: "빨간 등에 점이 있어요." },
            { id: "spider", emoji: "🕷️", name: "araña (거미)", rarity: "common", desc: "거미줄을 쳐요." },
            { id: "caterpillar", emoji: "🐛", name: "oruga (애벌레)", rarity: "common", desc: "곧 나비가 될 거예요." },
            { id: "cricket", emoji: "🦗", name: "grillo (귀뚜라미)", rarity: "common", desc: "밤에 노래해요." },
            { id: "apple", emoji: "🍎", name: "manzana (사과)", rarity: "common", desc: "빨갛고 아삭해요." },
            { id: "banana", emoji: "🍌", name: "plátano (바나나)", rarity: "common", desc: "달콤하고 노래요." },
            { id: "grape", emoji: "🍇", name: "uva (포도)", rarity: "common", desc: "스페인에선 새해에 12알 먹어요!" },
            { id: "orange", emoji: "🍊", name: "naranja (오렌지)", rarity: "common", desc: "비타민C가 가득!" },
            { id: "lemon", emoji: "🍋", name: "limón (레몬)", rarity: "common", desc: "시큼시큼해요." },
            { id: "strawberry", emoji: "🍓", name: "fresa (딸기)", rarity: "common", desc: "달콤한 봄의 과일." },
            { id: "tomato", emoji: "🍅", name: "tomate (토마토)", rarity: "common", desc: "토마티나 축제의 주인공!" },
            { id: "carrot", emoji: "🥕", name: "zanahoria (당근)", rarity: "common", desc: "토끼가 좋아해요." },
            { id: "corn", emoji: "🌽", name: "maíz (옥수수)", rarity: "common", desc: "노란 알갱이가 가득." },
            { id: "bread", emoji: "🍞", name: "pan (빵)", rarity: "common", desc: "갓 구운 냄새가 좋아요." },
            { id: "cheese", emoji: "🧀", name: "queso (치즈)", rarity: "common", desc: "고소하고 쫄깃해요." },
            { id: "egg", emoji: "🥚", name: "huevo (달걀)", rarity: "common", desc: "또 다른 알이네요?" },
            { id: "flower", emoji: "🌸", name: "flor (꽃)", rarity: "common", desc: "예쁘게 피었어요." },
            { id: "rose", emoji: "🌹", name: "rosa (장미)", rarity: "common", desc: "사랑의 꽃이에요." },
            { id: "sunflower", emoji: "🌻", name: "girasol (해바라기)", rarity: "common", desc: "해를 따라 움직여요." },
            { id: "tulip", emoji: "🌷", name: "tulipán (튤립)", rarity: "common", desc: "봄의 전령이에요." },
            { id: "tree", emoji: "🌳", name: "árbol (나무)", rarity: "common", desc: "든든하게 서 있어요." },
            { id: "cactus", emoji: "🌵", name: "cactus (선인장)", rarity: "common", desc: "물 없이도 잘 살아요." },
            { id: "leaf", emoji: "🍃", name: "hoja (잎)", rarity: "common", desc: "바람에 살랑살랑." },
            { id: "mushroom", emoji: "🍄", name: "seta (버섯)", rarity: "common", desc: "숲속에서 자라요." },
            { id: "star", emoji: "⭐", name: "estrella (별)", rarity: "common", desc: "밤하늘에 반짝여요." },
            { id: "cloud", emoji: "☁️", name: "nube (구름)", rarity: "common", desc: "하늘에 두둥실." },
            // ===== rare (레어) =====
            { id: "bull", emoji: "🐂", name: "toro (황소)", rarity: "rare", desc: "스페인의 상징이에요!" },
            { id: "owl", emoji: "🦉", name: "búho (부엉이)", rarity: "rare", desc: "밤에 공부하는 친구." },
            { id: "fox", emoji: "🦊", name: "zorro (여우)", rarity: "rare", desc: "영리하고 재빨라요." },
            { id: "octopus", emoji: "🐙", name: "pulpo (문어)", rarity: "rare", desc: "갈리시아식 pulpo가 유명해요!" },
            { id: "horse", emoji: "🐴", name: "caballo (말)", rarity: "rare", desc: "안달루시아 명마예요." },
            { id: "lion", emoji: "🦁", name: "león (사자)", rarity: "rare", desc: "용맹의 상징이에요." },
            { id: "wolf", emoji: "🐺", name: "lobo (늑대)", rarity: "rare", desc: "이베리아 늑대예요." },
            { id: "bear", emoji: "🐻", name: "oso (곰)", rarity: "rare", desc: "마드리드의 상징이에요!" },
            { id: "eagle", emoji: "🦅", name: "águila (독수리)", rarity: "rare", desc: "하늘의 제왕이에요." },
            { id: "turtle", emoji: "🐢", name: "tortuga (거북이)", rarity: "rare", desc: "오래오래 살아요." },
            { id: "butterfly", emoji: "🦋", name: "mariposa (나비)", rarity: "rare", desc: "예쁘게 팔랑팔랑." },
            { id: "deer", emoji: "🦌", name: "ciervo (사슴)", rarity: "rare", desc: "숲을 우아하게 달려요." },
            { id: "monkey", emoji: "🐵", name: "mono (원숭이)", rarity: "rare", desc: "나무를 잘 타요." },
            { id: "elephant", emoji: "🐘", name: "elefante (코끼리)", rarity: "rare", desc: "코가 아주 길어요." },
            { id: "penguin", emoji: "🐧", name: "pingüino (펭귄)", rarity: "rare", desc: "뒤뚱뒤뚱 걸어요." },
            { id: "dolphin", emoji: "🐬", name: "delfín (돌고래)", rarity: "rare", desc: "똑똑한 바다 친구." },
            { id: "shark", emoji: "🦈", name: "tiburón (상어)", rarity: "rare", desc: "바다의 사냥꾼이에요." },
            { id: "snake", emoji: "🐍", name: "serpiente (뱀)", rarity: "rare", desc: "스르륵 미끄러져요." },
            { id: "crab", emoji: "🦀", name: "cangrejo (게)", rarity: "rare", desc: "옆으로 걸어요." },
            { id: "swan", emoji: "🦢", name: "cisne (백조)", rarity: "rare", desc: "우아한 물새예요." },
            { id: "peacock_r", emoji: "🦚", name: "pavo real (공작)", rarity: "rare", desc: "화려한 깃털을 뽐내요." },
            { id: "flamingo", emoji: "🦩", name: "flamenco (홍학)", rarity: "rare", desc: "스페인 춤이랑 이름이 같아요!" },
            { id: "parrot", emoji: "🦜", name: "loro (앵무새)", rarity: "rare", desc: "말을 따라 해요." },
            { id: "hedgehog", emoji: "🦔", name: "erizo (고슴도치)", rarity: "rare", desc: "가시로 몸을 지켜요." },
            { id: "bat", emoji: "🦇", name: "murciélago (박쥐)", rarity: "rare", desc: "발렌시아의 상징이에요!" },
            { id: "paella", emoji: "🥘", name: "paella (파에야)", rarity: "rare", desc: "스페인 대표 요리예요!" },
            { id: "grapes_wine", emoji: "🍷", name: "vino (와인)", rarity: "rare", desc: "스페인 리오하 와인!" },
            { id: "churro", emoji: "🍩", name: "churro (츄러스)", rarity: "rare", desc: "초콜릿에 찍어 먹어요." },
            { id: "olive", emoji: "🫒", name: "aceituna (올리브)", rarity: "rare", desc: "스페인이 세계 1위예요." },
            { id: "rainbow", emoji: "🌈", name: "arcoíris (무지개)", rarity: "rare", desc: "비 온 뒤 나타나요." },
            // ===== epic (에픽) =====
            { id: "dragon", emoji: "🐲", name: "dragón (용)", rarity: "epic", desc: "카탈루냐 전설의 용이에요!" },
            { id: "unicorn", emoji: "🦄", name: "unicornio (유니콘)", rarity: "epic", desc: "아주 드문 전설의 동물!" },
            { id: "phoenix", emoji: "🔥", name: "fénix (불사조)", rarity: "epic", desc: "다시 타오르는 열정!" },
            { id: "whale", emoji: "🐋", name: "ballena (고래)", rarity: "epic", desc: "바다의 거인이에요." },
            { id: "tiger", emoji: "🐯", name: "tigre (호랑이)", rarity: "epic", desc: "용맹한 밀림의 왕." },
            { id: "panda", emoji: "🐼", name: "panda (판다)", rarity: "epic", desc: "대나무를 좋아해요." },
            { id: "koala", emoji: "🐨", name: "koala (코알라)", rarity: "epic", desc: "나무에 매달려 자요." },
            { id: "crocodile", emoji: "🐊", name: "cocodrilo (악어)", rarity: "epic", desc: "강가의 포식자예요." },
            { id: "rhino", emoji: "🦏", name: "rinoceronte (코뿔소)", rarity: "epic", desc: "단단한 뿔이 있어요." },
            { id: "hippo", emoji: "🦛", name: "hipopótamo (하마)", rarity: "epic", desc: "물속에서 지내요." },
            { id: "gorilla", emoji: "🦍", name: "gorila (고릴라)", rarity: "epic", desc: "힘이 아주 세요." },
            { id: "camel", emoji: "🐫", name: "camello (낙타)", rarity: "epic", desc: "사막을 건너요." },
            { id: "giraffe", emoji: "🦒", name: "jirafa (기린)", rarity: "epic", desc: "목이 아주 길어요." },
            { id: "volcano", emoji: "🌋", name: "volcán (화산)", rarity: "epic", desc: "용암을 뿜어요." },
            { id: "comet", emoji: "☄️", name: "cometa (혜성)", rarity: "epic", desc: "긴 꼬리를 그려요." },
            { id: "moon", emoji: "🌙", name: "luna (달)", rarity: "epic", desc: "밤을 밝혀줘요." },
            { id: "sun", emoji: "☀️", name: "sol (태양)", rarity: "epic", desc: "세상을 비춰요." },
            { id: "crystal", emoji: "💎", name: "cristal (수정)", rarity: "epic", desc: "반짝이는 보석이에요." },
            // ===== legendary (전설) =====
            { id: "alien", emoji: "👽", name: "alienígena (외계인)", rarity: "legendary", desc: "정체불명의 외계 생명체!" },
            { id: "ghost", emoji: "👾", name: "misterio (미스터리)", rarity: "legendary", desc: "정체를 알 수 없어요!" },
            { id: "robot", emoji: "🤖", name: "robot (로봇)", rarity: "legendary", desc: "수수께끼의 로봇이에요." },
            { id: "ninja", emoji: "🥷", name: "ninja (닌자)", rarity: "legendary", desc: "그림자처럼 나타나요!" },
            { id: "wizard", emoji: "🧙", name: "mago (마법사)", rarity: "legendary", desc: "신비한 마법을 부려요." },
            { id: "mermaid", emoji: "🧜", name: "sirena (인어)", rarity: "legendary", desc: "바닷속 전설의 존재!" },
            { id: "fairy", emoji: "🧚", name: "hada (요정)", rarity: "legendary", desc: "반짝이는 날개를 가졌어요." },
            // ===== [냐냐 PATCH] 도감 500 확장 =====
            { id: "squirrel", emoji: "🐿️", name: "ardilla (다람쥐)", rarity: "common", desc: "도토리를 잔뜩 모아요." },
            { id: "beetle", emoji: "🪲", name: "escarabajo (딱정벌레)", rarity: "common", desc: "반짝이는 등껍질이 멋져요." },
            { id: "worm", emoji: "🪱", name: "gusano (지렁이)", rarity: "common", desc: "흙을 건강하게 만들어요." },
            { id: "fly", emoji: "🪰", name: "mosca (파리)", rarity: "common", desc: "윙윙 날아다녀요." },
            { id: "mosquito", emoji: "🦟", name: "mosquito (모기)", rarity: "common", desc: "여름밤의 불청객이에요." },
            { id: "cockroach", emoji: "🪳", name: "cucaracha (바퀴벌레)", rarity: "common", desc: "엄청나게 빨라요!" },
            { id: "lizard", emoji: "🦎", name: "lagarto (도마뱀)", rarity: "common", desc: "햇볕 쬐는 걸 좋아해요." },
            { id: "shrimp", emoji: "🦐", name: "gamba (새우)", rarity: "common", desc: "스페인 요리의 단골이에요." },
            { id: "squid", emoji: "🦑", name: "calamar (오징어)", rarity: "common", desc: "먹물을 뿜어요." },
            { id: "lobster", emoji: "🦞", name: "langosta (랍스터)", rarity: "common", desc: "커다란 집게발이 있어요." },
            { id: "oyster", emoji: "🦪", name: "ostra (굴)", rarity: "common", desc: "진주를 품기도 해요." },
            { id: "snail2", emoji: "🐌", name: "caracol (달팽이)", rarity: "common", desc: "천천히, 하지만 꾸준히!" },
            { id: "dove", emoji: "🕊️", name: "paloma (비둘기)", rarity: "common", desc: "평화의 상징이에요." },
            { id: "rooster", emoji: "🐓", name: "gallo (수탉)", rarity: "common", desc: "아침을 알려줘요." },
            { id: "bird", emoji: "🐦", name: "pájaro (새)", rarity: "common", desc: "자유롭게 하늘을 날아요." },
            { id: "puppy", emoji: "🐕", name: "cachorro (강아지)", rarity: "common", desc: "꼬리를 흔들며 반겨줘요." },
            { id: "kitten", emoji: "🐈", name: "gatito (새끼고양이)", rarity: "common", desc: "호기심이 많아요." },
            { id: "donkey", emoji: "🫏", name: "burro (당나귀)", rarity: "common", desc: "묵묵히 짐을 날라요." },
            { id: "goose", emoji: "🪿", name: "ganso (거위)", rarity: "common", desc: "시끄럽게 울어요." },
            { id: "llama", emoji: "🦙", name: "llama (라마)", rarity: "common", desc: "안데스의 친구예요." },
            { id: "bison", emoji: "🦬", name: "bisonte (들소)", rarity: "common", desc: "힘이 아주 세요." },
            { id: "otter", emoji: "🦦", name: "nutria (수달)", rarity: "common", desc: "조개를 깨먹어요." },
            { id: "skunk", emoji: "🦨", name: "mofeta (스컹크)", rarity: "common", desc: "가까이 가면 안 돼요!" },
            { id: "badger", emoji: "🦡", name: "tejón (오소리)", rarity: "common", desc: "땅굴을 잘 파요." },
            { id: "sloth", emoji: "🦥", name: "perezoso (나무늘보)", rarity: "common", desc: "아주 느긋해요." },
            { id: "raccoon", emoji: "🦝", name: "mapache (너구리)", rarity: "common", desc: "손이 야무져요." },
            { id: "mole", emoji: "🐀", name: "topo (두더지)", rarity: "common", desc: "땅속에서 살아요." },
            { id: "bug", emoji: "🐛", name: "bicho (벌레)", rarity: "common", desc: "작지만 씩씩해요." },
            { id: "peach", emoji: "🍑", name: "melocotón (복숭아)", rarity: "common", desc: "달콤한 향이 나요." },
            { id: "pear", emoji: "🍐", name: "pera (배)", rarity: "common", desc: "시원하고 아삭해요." },
            { id: "cherry", emoji: "🍒", name: "cereza (체리)", rarity: "common", desc: "새콤달콤해요." },
            { id: "watermelon", emoji: "🍉", name: "sandía (수박)", rarity: "common", desc: "여름엔 역시 수박!" },
            { id: "melon", emoji: "🍈", name: "melón (멜론)", rarity: "common", desc: "향이 진해요." },
            { id: "pineapple", emoji: "🍍", name: "piña (파인애플)", rarity: "common", desc: "톡 쏘는 단맛이에요." },
            { id: "mango", emoji: "🥭", name: "mango (망고)", rarity: "common", desc: "열대의 달콤함!" },
            { id: "coconut", emoji: "🥥", name: "coco (코코넛)", rarity: "common", desc: "단단한 껍질 속에 물이 있어요." },
            { id: "kiwi", emoji: "🥝", name: "kiwi (키위)", rarity: "common", desc: "비타민이 가득해요." },
            { id: "avocado", emoji: "🥑", name: "aguacate (아보카도)", rarity: "common", desc: "고소하고 부드러워요." },
            { id: "potato", emoji: "🥔", name: "patata (감자)", rarity: "common", desc: "스페인 오믈렛의 주인공!" },
            { id: "onion", emoji: "🧅", name: "cebolla (양파)", rarity: "common", desc: "눈물이 나게 해요." },
            { id: "garlic", emoji: "🧄", name: "ajo (마늘)", rarity: "common", desc: "향이 강렬해요." },
            { id: "pepper", emoji: "🌶️", name: "pimiento (고추)", rarity: "common", desc: "매콤해요!" },
            { id: "cucumber", emoji: "🥒", name: "pepino (오이)", rarity: "common", desc: "아삭하고 시원해요." },
            { id: "broccoli", emoji: "🥦", name: "brócoli (브로콜리)", rarity: "common", desc: "건강에 좋아요." },
            { id: "lettuce", emoji: "🥬", name: "lechuga (상추)", rarity: "common", desc: "샐러드의 기본이에요." },
            { id: "eggplant", emoji: "🍆", name: "berenjena (가지)", rarity: "common", desc: "보랏빛이 예뻐요." },
            { id: "peanut", emoji: "🥜", name: "cacahuete (땅콩)", rarity: "common", desc: "고소해요." },
            { id: "chestnut", emoji: "🌰", name: "castaña (밤)", rarity: "common", desc: "가을의 맛이에요." },
            { id: "rice", emoji: "🍚", name: "arroz (쌀)", rarity: "common", desc: "파에야의 기본이에요." },
            { id: "milk", emoji: "🥛", name: "leche (우유)", rarity: "common", desc: "뼈를 튼튼하게 해줘요." },
            { id: "coffee", emoji: "☕", name: "café (커피)", rarity: "common", desc: "스페인 사람들의 아침이에요." },
            { id: "tea", emoji: "🍵", name: "té (차)", rarity: "common", desc: "마음이 편안해져요." },
            { id: "water", emoji: "💧", name: "agua (물)", rarity: "common", desc: "생명의 근원이에요." },
            { id: "salt", emoji: "🧂", name: "sal (소금)", rarity: "common", desc: "바다에서 왔어요." },
            { id: "honey", emoji: "🍯", name: "miel (꿀)", rarity: "common", desc: "벌들의 선물이에요." },
            { id: "butter", emoji: "🧈", name: "mantequilla (버터)", rarity: "common", desc: "고소하고 부드러워요." },
            { id: "cookie", emoji: "🍪", name: "galleta (쿠키)", rarity: "common", desc: "달콤한 간식이에요." },
            { id: "cake", emoji: "🍰", name: "tarta (케이크)", rarity: "common", desc: "축하할 때 먹어요." },
            { id: "icecream", emoji: "🍦", name: "helado (아이스크림)", rarity: "common", desc: "더위를 식혀줘요." },
            { id: "chocolate", emoji: "🍫", name: "chocolate (초콜릿)", rarity: "common", desc: "churro와 찰떡궁합!" },
            { id: "candy", emoji: "🍬", name: "caramelo (사탕)", rarity: "common", desc: "입안이 달콤해져요." },
            { id: "donut", emoji: "🍩", name: "dónut (도넛)", rarity: "common", desc: "동그란 달콤함." },
            { id: "pizza", emoji: "🍕", name: "pizza (피자)", rarity: "common", desc: "모두가 좋아해요." },
            { id: "soup", emoji: "🍲", name: "sopa (수프)", rarity: "common", desc: "따뜻하게 몸을 녹여줘요." },
            { id: "salad", emoji: "🥗", name: "ensalada (샐러드)", rarity: "common", desc: "신선하고 건강해요." },
            { id: "sandwich", emoji: "🥪", name: "bocadillo (샌드위치)", rarity: "common", desc: "스페인식 바게트 샌드위치!" },
            { id: "taco", emoji: "🌮", name: "taco (타코)", rarity: "common", desc: "라틴의 맛이에요." },
            { id: "burrito", emoji: "🌯", name: "burrito (부리토)", rarity: "common", desc: "속이 꽉 찼어요." },
            { id: "croissant", emoji: "🥐", name: "cruasán (크루아상)", rarity: "common", desc: "아침 식사로 좋아요." },
            { id: "baguette", emoji: "🥖", name: "barra de pan (바게트)", rarity: "common", desc: "바삭한 겉면이 매력이에요." },
            { id: "pancake", emoji: "🥞", name: "tortita (팬케이크)", rarity: "common", desc: "시럽을 듬뿍!" },
            { id: "popcorn", emoji: "🍿", name: "palomitas (팝콘)", rarity: "common", desc: "영화엔 역시 팝콘!" },
            { id: "grass", emoji: "🌿", name: "hierba (풀)", rarity: "common", desc: "싱그러운 초록이에요." },
            { id: "clover", emoji: "🍀", name: "trébol (클로버)", rarity: "common", desc: "행운을 가져다줘요." },
            { id: "palm", emoji: "🌴", name: "palmera (야자수)", rarity: "common", desc: "해변이 떠올라요." },
            { id: "pine", emoji: "🌲", name: "pino (소나무)", rarity: "common", desc: "사시사철 푸르러요." },
            { id: "seedling", emoji: "🌱", name: "brote (새싹)", rarity: "common", desc: "이제 막 자라기 시작했어요." },
            { id: "herb", emoji: "🌾", name: "espiga (이삭)", rarity: "common", desc: "황금빛으로 익었어요." },
            { id: "maple", emoji: "🍁", name: "hoja de arce (단풍잎)", rarity: "common", desc: "가을을 알려줘요." },
            { id: "bouquet", emoji: "💐", name: "ramo (꽃다발)", rarity: "common", desc: "마음을 전해요." },
            { id: "hibiscus", emoji: "🌺", name: "hibisco (히비스커스)", rarity: "common", desc: "열대의 꽃이에요." },
            { id: "blossom", emoji: "🌸", name: "flor de cerezo (벚꽃)", rarity: "common", desc: "봄이 왔어요." },
            { id: "daisy", emoji: "🌼", name: "margarita (데이지)", rarity: "common", desc: "소박하고 예뻐요." },
            { id: "wilted", emoji: "🥀", name: "flor marchita (시든 꽃)", rarity: "common", desc: "그래도 아름다워요." },
            { id: "rock", emoji: "🪨", name: "roca (바위)", rarity: "common", desc: "묵직하고 단단해요." },
            { id: "shell", emoji: "🐚", name: "concha (조개껍데기)", rarity: "common", desc: "파도 소리가 들려요." },
            { id: "feather", emoji: "🪶", name: "pluma (깃털)", rarity: "common", desc: "가볍게 날아가요." },
            { id: "wind", emoji: "🌬️", name: "viento (바람)", rarity: "common", desc: "시원하게 불어와요." },
            { id: "rain", emoji: "🌧️", name: "lluvia (비)", rarity: "common", desc: "대지를 적셔줘요." },
            { id: "snowflake", emoji: "❄️", name: "copo de nieve (눈송이)", rarity: "common", desc: "하나하나 모양이 달라요." },
            { id: "fog", emoji: "🌫️", name: "niebla (안개)", rarity: "common", desc: "몽환적인 분위기예요." },
            { id: "droplet", emoji: "💦", name: "gotas (물방울)", rarity: "common", desc: "반짝반짝 빛나요." },
            { id: "bubble", emoji: "🫧", name: "burbuja (거품)", rarity: "common", desc: "톡 하고 터져요." },
            { id: "sprout2", emoji: "☘️", name: "trébol de tres (세잎클로버)", rarity: "common", desc: "흔하지만 소중해요." },
            { id: "cricket2", emoji: "🦗", name: "grillo (귀뚜라미)", rarity: "common", desc: "가을밤에 울어요." },
            { id: "dragonfly", emoji: "🪳", name: "libélula (잠자리)", rarity: "common", desc: "날개가 투명해요." },
            { id: "jaguar", emoji: "🐆", name: "jaguar (재규어)", rarity: "rare", desc: "라틴아메리카의 사냥꾼!" },
            { id: "puma", emoji: "🐈‍⬛", name: "puma (퓨마)", rarity: "rare", desc: "안데스를 누벼요." },
            { id: "condor", emoji: "🦅", name: "cóndor (콘도르)", rarity: "rare", desc: "안데스의 왕이에요." },
            { id: "toucan", emoji: "🦜", name: "tucán (큰부리새)", rarity: "rare", desc: "부리가 화려해요." },
            { id: "iguana", emoji: "🦎", name: "iguana (이구아나)", rarity: "rare", desc: "고대의 모습을 간직했어요." },
            { id: "armadillo", emoji: "🦔", name: "armadillo (아르마딜로)", rarity: "rare", desc: "단단한 갑옷을 둘렀어요." },
            { id: "anteater", emoji: "🐜", name: "oso hormiguero (개미핥기)", rarity: "rare", desc: "긴 혀로 개미를 먹어요." },
            { id: "capybara", emoji: "🦫", name: "capibara (카피바라)", rarity: "rare", desc: "세상에서 제일 느긋해요." },
            { id: "chinchilla", emoji: "🐹", name: "chinchilla (친칠라)", rarity: "rare", desc: "털이 아주 부드러워요." },
            { id: "alpaca", emoji: "🦙", name: "alpaca (알파카)", rarity: "rare", desc: "포근한 털을 가졌어요." },
            { id: "tapir", emoji: "🐗", name: "tapir (맥)", rarity: "rare", desc: "코가 길쭉해요." },
            { id: "piranha", emoji: "🐟", name: "piraña (피라냐)", rarity: "rare", desc: "이빨이 날카로워요." },
            { id: "manatee", emoji: "🐋", name: "manatí (해우)", rarity: "rare", desc: "바다의 소예요." },
            { id: "seal", emoji: "🦭", name: "foca (물개)", rarity: "rare", desc: "박수를 잘 쳐요." },
            { id: "walrus", emoji: "🦭", name: "morsa (바다코끼리)", rarity: "rare", desc: "긴 엄니가 인상적이에요." },
            { id: "orca", emoji: "🐋", name: "orca (범고래)", rarity: "rare", desc: "바다의 최상위 포식자!" },
            { id: "jellyfish", emoji: "🪼", name: "medusa (해파리)", rarity: "rare", desc: "투명하게 떠다녀요." },
            { id: "seahorse", emoji: "🐴", name: "caballito de mar (해마)", rarity: "rare", desc: "아빠가 새끼를 품어요." },
            { id: "starfish", emoji: "⭐", name: "estrella de mar (불가사리)", rarity: "rare", desc: "팔이 다시 자라요." },
            { id: "coral", emoji: "🪸", name: "coral (산호)", rarity: "rare", desc: "바다의 정원이에요." },
            { id: "pelican", emoji: "🦢", name: "pelícano (펠리컨)", rarity: "rare", desc: "부리 주머니가 커요." },
            { id: "stork", emoji: "🕊️", name: "cigüeña (황새)", rarity: "rare", desc: "스페인 지붕 위의 손님!" },
            { id: "heron", emoji: "🦩", name: "garza (왜가리)", rarity: "rare", desc: "우아하게 서 있어요." },
            { id: "kingfisher", emoji: "🐦", name: "martín pescador (물총새)", rarity: "rare", desc: "물고기 사냥의 명수!" },
            { id: "hummingbird", emoji: "🐦", name: "colibrí (벌새)", rarity: "rare", desc: "공중에 멈춰 있을 수 있어요." },
            { id: "falcon", emoji: "🦅", name: "halcón (매)", rarity: "rare", desc: "눈이 아주 좋아요." },
            { id: "vulture", emoji: "🦅", name: "buitre (독수리)", rarity: "rare", desc: "하늘을 맴돌아요." },
            { id: "nightingale", emoji: "🐦", name: "ruiseñor (나이팅게일)", rarity: "rare", desc: "노래가 아름다워요." },
            { id: "sardine", emoji: "🐟", name: "sardina (정어리)", rarity: "rare", desc: "스페인에선 구워 먹어요." },
            { id: "anchovy", emoji: "🐟", name: "boquerón (멸치)", rarity: "rare", desc: "타파스의 단골이에요." },
            { id: "tuna", emoji: "🐟", name: "atún (참치)", rarity: "rare", desc: "바다를 빠르게 헤엄쳐요." },
            { id: "mussel", emoji: "🦪", name: "mejillón (홍합)", rarity: "rare", desc: "파에야에 들어가요." },
            { id: "tapas", emoji: "🍢", name: "tapas (타파스)", rarity: "rare", desc: "스페인의 작은 안주들!" },
            { id: "gazpacho", emoji: "🥣", name: "gazpacho (가스파초)", rarity: "rare", desc: "차갑게 먹는 토마토 수프." },
            { id: "tortilla", emoji: "🍳", name: "tortilla (토르티야)", rarity: "rare", desc: "감자 오믈렛이에요." },
            { id: "jamon", emoji: "🥓", name: "jamón (하몽)", rarity: "rare", desc: "스페인의 자랑이에요." },
            { id: "sangria", emoji: "🍷", name: "sangría (상그리아)", rarity: "rare", desc: "과일이 든 와인이에요." },
            { id: "flan", emoji: "🍮", name: "flan (플란)", rarity: "rare", desc: "달콤한 커스터드 푸딩." },
            { id: "guitar", emoji: "🎸", name: "guitarra (기타)", rarity: "rare", desc: "플라멩코의 소리예요." },
            { id: "castanets", emoji: "🥁", name: "castañuelas (캐스터네츠)", rarity: "rare", desc: "딱딱 경쾌한 소리!" },
            { id: "fan", emoji: "🪭", name: "abanico (부채)", rarity: "rare", desc: "플라멩코 무희의 필수품." },
            { id: "flamenco", emoji: "💃", name: "flamenco (플라멩코)", rarity: "rare", desc: "정열의 춤이에요." },
            { id: "matador", emoji: "🕺", name: "matador (투우사)", rarity: "rare", desc: "붉은 천을 휘둘러요." },
            { id: "windmill", emoji: "🏰", name: "molino (풍차)", rarity: "rare", desc: "돈키호테가 돌진했던 그것!" },
            { id: "castle", emoji: "🏰", name: "castillo (성)", rarity: "rare", desc: "중세의 기운이 느껴져요." },
            { id: "cathedral", emoji: "⛪", name: "catedral (대성당)", rarity: "rare", desc: "웅장하고 아름다워요." },
            { id: "lighthouse", emoji: "🗼", name: "faro (등대)", rarity: "rare", desc: "밤바다를 밝혀줘요." },
            { id: "shipwreck", emoji: "⚓", name: "naufragio (난파선)", rarity: "rare", desc: "보물이 잠들어 있을까요?" },
            { id: "compass", emoji: "🧭", name: "brújula (나침반)", rarity: "rare", desc: "길을 알려줘요." },
            { id: "hourglass", emoji: "⏳", name: "reloj de arena (모래시계)", rarity: "rare", desc: "시간이 흘러가요." },
            { id: "key", emoji: "🗝️", name: "llave (열쇠)", rarity: "rare", desc: "무엇을 열 수 있을까요?" },
            { id: "lantern", emoji: "🏮", name: "farol (등불)", rarity: "rare", desc: "은은하게 빛나요." },
            { id: "scroll", emoji: "📜", name: "pergamino (두루마리)", rarity: "rare", desc: "고대의 지식이 담겼어요." },
            { id: "potion", emoji: "🧪", name: "poción (물약)", rarity: "rare", desc: "무슨 효과가 있을까요?" },
            { id: "telescope", emoji: "🔭", name: "telescopio (망원경)", rarity: "rare", desc: "별을 관찰해요." },
            { id: "anchor2", emoji: "⚓", name: "ancla (닻)", rarity: "rare", desc: "배를 붙잡아줘요." },
            { id: "map", emoji: "🗺️", name: "mapa (지도)", rarity: "rare", desc: "모험의 시작이에요." },
            { id: "gem_r", emoji: "💠", name: "gema (보석)", rarity: "rare", desc: "맑게 빛나요." },
            { id: "bell", emoji: "🔔", name: "campana (종)", rarity: "rare", desc: "맑은 소리가 울려요." },
            { id: "mask", emoji: "🎭", name: "máscara (가면)", rarity: "rare", desc: "축제의 얼굴이에요." },
            { id: "griffin", emoji: "🦅", name: "grifo (그리핀)", rarity: "epic", desc: "독수리와 사자의 혼합체!" },
            { id: "pegasus", emoji: "🐴", name: "pegaso (페가수스)", rarity: "epic", desc: "날개 달린 백마예요." },
            { id: "centaur", emoji: "🏹", name: "centauro (켄타우로스)", rarity: "epic", desc: "반은 사람, 반은 말!" },
            { id: "minotaur", emoji: "🐂", name: "minotauro (미노타우로스)", rarity: "epic", desc: "미궁의 수호자." },
            { id: "mermaid_2", emoji: "🧜", name: "sirena (인어)", rarity: "epic", desc: "노래로 뱃사람을 홀려요." },
            { id: "kraken", emoji: "🐙", name: "kraken (크라켄)", rarity: "epic", desc: "배를 삼키는 바다 괴물!" },
            { id: "hydra", emoji: "🐉", name: "hidra (히드라)", rarity: "epic", desc: "머리가 여러 개예요." },
            { id: "basilisk", emoji: "🐍", name: "basilisco (바실리스크)", rarity: "epic", desc: "눈을 마주치면 안 돼요!" },
            { id: "chimera", emoji: "🦁", name: "quimera (키메라)", rarity: "epic", desc: "여러 짐승이 섞였어요." },
            { id: "cerberus", emoji: "🐕", name: "cerbero (케르베로스)", rarity: "epic", desc: "지옥문을 지켜요." },
            { id: "golem", emoji: "🗿", name: "gólem (골렘)", rarity: "epic", desc: "돌로 만들어진 수호자." },
            { id: "gargoyle", emoji: "🦇", name: "gárgola (가고일)", rarity: "epic", desc: "성당 지붕에 앉아 있어요." },
            { id: "werewolf", emoji: "🐺", name: "hombre lobo (늑대인간)", rarity: "epic", desc: "보름달에 변신해요." },
            { id: "vampire", emoji: "🧛", name: "vampiro (뱀파이어)", rarity: "epic", desc: "밤에만 나타나요." },
            { id: "titan", emoji: "🗿", name: "titán (티탄)", rarity: "epic", desc: "거대한 고대 존재." },
            { id: "kelpie", emoji: "🐎", name: "kelpie (켈피)", rarity: "epic", desc: "물가에 나타나는 말." },
            { id: "salamander", emoji: "🦎", name: "salamandra (불도마뱀)", rarity: "epic", desc: "불 속에서 산대요." },
            { id: "thunderbird", emoji: "🦅", name: "ave del trueno (천둥새)", rarity: "epic", desc: "날개짓이 천둥을 불러요." },
            { id: "leviathan", emoji: "🐳", name: "leviatán (리바이어던)", rarity: "epic", desc: "바다의 거대한 존재." },
            { id: "sphinx", emoji: "🦁", name: "esfinge (스핑크스)", rarity: "epic", desc: "수수께끼를 내요." },
            { id: "banshee", emoji: "👻", name: "banshee (밴시)", rarity: "epic", desc: "울음소리가 불길해요." },
            { id: "djinn", emoji: "🧞", name: "genio (지니)", rarity: "epic", desc: "소원을 들어줄까요?" },
            { id: "elf", emoji: "🧝", name: "elfo (엘프)", rarity: "epic", desc: "숲의 지혜로운 종족." },
            { id: "dwarf", emoji: "🧔", name: "enano (드워프)", rarity: "epic", desc: "광산의 장인이에요." },
            { id: "troll", emoji: "👹", name: "trol (트롤)", rarity: "epic", desc: "다리 밑에 숨어 있어요." },
            { id: "goblin", emoji: "👺", name: "duende (고블린)", rarity: "epic", desc: "장난이 심해요." },
            { id: "fairy_2", emoji: "🧚", name: "hada (요정)", rarity: "epic", desc: "반짝이는 가루를 뿌려요." },
            { id: "mermaid_k", emoji: "🧜‍♂️", name: "tritón (트리톤)", rarity: "epic", desc: "바다의 왕자예요." },
            { id: "nebula", emoji: "🌌", name: "nebulosa (성운)", rarity: "epic", desc: "별이 태어나는 곳." },
            { id: "blackhole", emoji: "🕳️", name: "agujero negro (블랙홀)", rarity: "epic", desc: "빛조차 빠져나갈 수 없어요." },
            { id: "galaxy", emoji: "🌠", name: "galaxia (은하)", rarity: "epic", desc: "수많은 별들의 고향." },
            { id: "aurora", emoji: "🌈", name: "aurora (오로라)", rarity: "epic", desc: "하늘의 커튼이에요." },
            { id: "meteor", emoji: "☄️", name: "meteorito (운석)", rarity: "epic", desc: "하늘에서 떨어졌어요." },
            { id: "eclipse", emoji: "🌑", name: "eclipse (일식)", rarity: "epic", desc: "해가 사라져요." },
            { id: "supernova", emoji: "💥", name: "supernova (초신성)", rarity: "epic", desc: "별의 마지막 폭발!" },
            { id: "tornado", emoji: "🌪️", name: "tornado (토네이도)", rarity: "epic", desc: "모든 걸 휩쓸어요." },
            { id: "tsunami", emoji: "🌊", name: "tsunami (해일)", rarity: "epic", desc: "거대한 파도예요." },
            { id: "lightning", emoji: "⚡", name: "rayo (번개)", rarity: "epic", desc: "순식간에 번쩍!" },
            { id: "labyrinth", emoji: "🌀", name: "laberinto (미궁)", rarity: "epic", desc: "빠져나올 수 있을까요?" },
            { id: "mirage", emoji: "🏜️", name: "espejismo (신기루)", rarity: "epic", desc: "있는 듯 없는 듯." },
            { id: "quetzal", emoji: "🦜", name: "quetzalcóatl (케찰코아틀)", rarity: "legendary", desc: "깃털 달린 뱀신이에요!" },
            { id: "elgato", emoji: "🐈‍⬛", name: "el gato eterno (영원의 고양이)", rarity: "legendary", desc: "시간을 넘나든대요." },
            { id: "dondragon", emoji: "🐲", name: "dragón dorado (황금용)", rarity: "legendary", desc: "전설 속 최강의 존재!" },
            { id: "timekeeper", emoji: "⌛", name: "guardián del tiempo (시간의 수호자)", rarity: "legendary", desc: "시간을 지켜요." },
            { id: "cosmos", emoji: "🌌", name: "cosmos (코스모스)", rarity: "legendary", desc: "우주 그 자체예요." },
            { id: "worldtree", emoji: "🌳", name: "árbol del mundo (세계수)", rarity: "legendary", desc: "모든 생명의 뿌리." },
            { id: "philosopher", emoji: "🧙‍♂️", name: "piedra filosofal (현자의 돌)", rarity: "legendary", desc: "모든 걸 금으로 바꾼대요." },
            { id: "infinity", emoji: "♾️", name: "infinito (무한)", rarity: "legendary", desc: "끝이 없어요." },
            { id: "elrey", emoji: "👑", name: "el rey (왕)", rarity: "legendary", desc: "모든 것 위에 군림해요." },
            { id: "nyanya", emoji: "🌟", name: "nyanya (냐냐)", rarity: "legendary", desc: "전설의 스페인어 마스터!" },
            { id: "hispania", emoji: "🇪🇸", name: "hispania (히스파니아)", rarity: "legendary", desc: "스페인의 옛 이름이에요." },
            { id: "elsol", emoji: "🔆", name: "el sol eterno (영원한 태양)", rarity: "legendary", desc: "절대 지지 않아요." },
            { id: "libro", emoji: "📖", name: "libro (책)", rarity: "common", desc: "지식이 담겨 있어요." },
            { id: "lapiz", emoji: "✏️", name: "lápiz (연필)", rarity: "common", desc: "무엇이든 써 내려가요." },
            { id: "silla", emoji: "🪑", name: "silla (의자)", rarity: "common", desc: "편히 앉으세요." },
            { id: "mesa", emoji: "🪑", name: "mesa (탁자)", rarity: "common", desc: "함께 둘러앉아요." },
            { id: "puerta", emoji: "🚪", name: "puerta (문)", rarity: "common", desc: "새로운 곳으로 이어져요." },
            { id: "ventana", emoji: "🪟", name: "ventana (창문)", rarity: "common", desc: "바깥이 보여요." },
            { id: "reloj", emoji: "⏰", name: "reloj (시계)", rarity: "common", desc: "시간을 알려줘요." },
            { id: "espejo", emoji: "🪞", name: "espejo (거울)", rarity: "common", desc: "자신을 비춰봐요." },
            { id: "cama", emoji: "🛏️", name: "cama (침대)", rarity: "common", desc: "포근한 잠자리예요." },
            { id: "bano", emoji: "🛁", name: "bañera (욕조)", rarity: "common", desc: "따뜻한 물에 몸을 담가요." },
            { id: "jabon", emoji: "🧼", name: "jabón (비누)", rarity: "common", desc: "깨끗하게 씻어요." },
            { id: "toalla", emoji: "🧻", name: "toalla (수건)", rarity: "common", desc: "물기를 닦아요." },
            { id: "zapato", emoji: "👟", name: "zapato (신발)", rarity: "common", desc: "어디든 갈 수 있어요." },
            { id: "camisa", emoji: "👕", name: "camisa (셔츠)", rarity: "common", desc: "단정해 보여요." },
            { id: "pantalon", emoji: "👖", name: "pantalón (바지)", rarity: "common", desc: "편안해요." },
            { id: "sombrero", emoji: "👒", name: "sombrero (모자)", rarity: "common", desc: "햇빛을 가려줘요." },
            { id: "gafas", emoji: "👓", name: "gafas (안경)", rarity: "common", desc: "세상이 또렷해져요." },
            { id: "bolso", emoji: "👜", name: "bolso (가방)", rarity: "common", desc: "필요한 걸 담아요." },
            { id: "paraguas", emoji: "☂️", name: "paraguas (우산)", rarity: "common", desc: "비를 막아줘요." },
            { id: "guante", emoji: "🧤", name: "guantes (장갑)", rarity: "common", desc: "손이 따뜻해요." },
            { id: "bufanda", emoji: "🧣", name: "bufanda (목도리)", rarity: "common", desc: "겨울에 필수예요." },
            { id: "anillo", emoji: "💍", name: "anillo (반지)", rarity: "common", desc: "약속의 징표예요." },
            { id: "corona", emoji: "👑", name: "corona (왕관)", rarity: "common", desc: "빛나는 권위예요." },
            { id: "regalo", emoji: "🎁", name: "regalo (선물)", rarity: "common", desc: "기쁨을 전해요." },
            { id: "globo", emoji: "🎈", name: "globo (풍선)", rarity: "common", desc: "하늘로 날아가요." },
            { id: "pelota", emoji: "⚽", name: "pelota (공)", rarity: "common", desc: "함께 놀아요!" },
            { id: "bici", emoji: "🚲", name: "bicicleta (자전거)", rarity: "common", desc: "페달을 밟아요." },
            { id: "coche", emoji: "🚗", name: "coche (자동차)", rarity: "common", desc: "멀리 갈 수 있어요." },
            { id: "tren", emoji: "🚂", name: "tren (기차)", rarity: "common", desc: "칙칙폭폭!" },
            { id: "avion", emoji: "✈️", name: "avión (비행기)", rarity: "common", desc: "하늘을 날아요." },
            { id: "barco", emoji: "⛵", name: "barco (배)", rarity: "common", desc: "바다를 건너요." },
            { id: "cohete", emoji: "🚀", name: "cohete (로켓)", rarity: "common", desc: "우주로 향해요." },
            { id: "casa", emoji: "🏠", name: "casa (집)", rarity: "common", desc: "가장 편안한 곳이에요." },
            { id: "escuela", emoji: "🏫", name: "escuela (학교)", rarity: "common", desc: "배움의 터전이에요." },
            { id: "tienda", emoji: "🏪", name: "tienda (가게)", rarity: "common", desc: "필요한 걸 살 수 있어요." },
            { id: "hospital", emoji: "🏥", name: "hospital (병원)", rarity: "common", desc: "아프면 가는 곳." },
            { id: "banco", emoji: "🏦", name: "banco (은행)", rarity: "common", desc: "돈을 보관해요." },
            { id: "parque", emoji: "🏞️", name: "parque (공원)", rarity: "common", desc: "산책하기 좋아요." },
            { id: "playa", emoji: "🏖️", name: "playa (해변)", rarity: "common", desc: "스페인의 여름!" },
            { id: "montana", emoji: "⛰️", name: "montaña (산)", rarity: "common", desc: "정상까지 올라가요." },
            { id: "rio", emoji: "🏞️", name: "río (강)", rarity: "common", desc: "유유히 흘러가요." },
            { id: "puente", emoji: "🌉", name: "puente (다리)", rarity: "common", desc: "양쪽을 이어줘요." },
            { id: "carta", emoji: "💌", name: "carta (편지)", rarity: "common", desc: "마음을 담아 보내요." },
            { id: "musica", emoji: "🎵", name: "música (음악)", rarity: "common", desc: "마음을 울려요." },
            { id: "piano", emoji: "🎹", name: "piano (피아노)", rarity: "common", desc: "건반을 두드려요." },
            { id: "violin", emoji: "🎻", name: "violín (바이올린)", rarity: "common", desc: "선율이 아름다워요." },
            { id: "tambor", emoji: "🥁", name: "tambor (북)", rarity: "common", desc: "리듬을 만들어요." },
            { id: "pintura", emoji: "🎨", name: "pintura (그림)", rarity: "common", desc: "색으로 표현해요." },
            { id: "camara", emoji: "📷", name: "cámara (카메라)", rarity: "common", desc: "순간을 담아요." },
            { id: "pelicula", emoji: "🎬", name: "película (영화)", rarity: "common", desc: "이야기를 보여줘요." },
            { id: "juego", emoji: "🎮", name: "juego (게임)", rarity: "common", desc: "즐겁게 놀아요." },
            { id: "dado", emoji: "🎲", name: "dado (주사위)", rarity: "common", desc: "운을 시험해요." },
            { id: "carta_j", emoji: "🃏", name: "naipe (카드)", rarity: "common", desc: "한 판 어때요?" },
            { id: "ajedrez", emoji: "♟️", name: "ajedrez (체스)", rarity: "common", desc: "머리를 써야 해요." },
            { id: "dinero", emoji: "💰", name: "dinero (돈)", rarity: "common", desc: "필요하지만 전부는 아니에요." },
            { id: "moneda", emoji: "🪙", name: "moneda (동전)", rarity: "common", desc: "짤랑짤랑." },
            { id: "fuego", emoji: "🔥", name: "fuego (불)", rarity: "common", desc: "따뜻하지만 위험해요." },
            { id: "hielo", emoji: "🧊", name: "hielo (얼음)", rarity: "common", desc: "차갑고 투명해요." },
            { id: "luz", emoji: "💡", name: "luz (빛)", rarity: "common", desc: "어둠을 밝혀요." },
            { id: "sombra", emoji: "🌑", name: "sombra (그림자)", rarity: "common", desc: "빛이 있어야 생겨요." },
            { id: "corazon", emoji: "❤️", name: "corazón (심장)", rarity: "common", desc: "사랑이 살아 있어요." },
            { id: "cerebro", emoji: "🧠", name: "cerebro (뇌)", rarity: "common", desc: "생각의 중심이에요." },
            { id: "ojo", emoji: "👁️", name: "ojo (눈)", rarity: "common", desc: "세상을 봐요." },
            { id: "mano", emoji: "✋", name: "mano (손)", rarity: "common", desc: "무엇이든 만들어요." },
            { id: "pie", emoji: "🦶", name: "pie (발)", rarity: "common", desc: "어디로든 데려가줘요." },
            { id: "oreja", emoji: "👂", name: "oreja (귀)", rarity: "common", desc: "소리를 들어요." },
            { id: "boca", emoji: "👄", name: "boca (입)", rarity: "common", desc: "말하고 먹어요." },
            { id: "diente", emoji: "🦷", name: "diente (이)", rarity: "common", desc: "잘 닦아야 해요." },
            { id: "hueso", emoji: "🦴", name: "hueso (뼈)", rarity: "common", desc: "몸을 지탱해요." },
            { id: "sonrisa", emoji: "😊", name: "sonrisa (미소)", rarity: "common", desc: "기분이 좋아져요." },
            { id: "beso", emoji: "💋", name: "beso (키스)", rarity: "common", desc: "애정의 표현이에요." },
            { id: "abrazo", emoji: "🤗", name: "abrazo (포옹)", rarity: "common", desc: "따뜻해요." },
            { id: "suerte", emoji: "🍀", name: "suerte (행운)", rarity: "common", desc: "오늘도 함께하길!" },
            { id: "sueno", emoji: "💤", name: "sueño (꿈)", rarity: "common", desc: "잠들면 만나요." },
            { id: "tiempo", emoji: "⏱️", name: "tiempo (시간)", rarity: "common", desc: "모두에게 공평해요." },
            { id: "viaje", emoji: "🧳", name: "viaje (여행)", rarity: "common", desc: "새로운 세상으로!" },
            { id: "fiesta", emoji: "🎉", name: "fiesta (파티)", rarity: "common", desc: "스페인 사람들이 사랑해요." },
            { id: "baile", emoji: "🕺", name: "baile (춤)", rarity: "common", desc: "몸으로 말해요." },
            { id: "cancion", emoji: "🎤", name: "canción (노래)", rarity: "common", desc: "목소리로 전해요." },
            { id: "risa", emoji: "😂", name: "risa (웃음)", rarity: "common", desc: "최고의 약이에요." },
            { id: "nube2", emoji: "☁️", name: "nube (구름)", rarity: "common", desc: "하늘에 떠 있어요." },
            { id: "estrella2", emoji: "✨", name: "estrella (별)", rarity: "common", desc: "밤하늘을 수놓아요." },
            { id: "cielo", emoji: "🌤️", name: "cielo (하늘)", rarity: "common", desc: "끝없이 펼쳐져요." },
            { id: "tierra", emoji: "🌍", name: "tierra (지구)", rarity: "common", desc: "우리의 집이에요." },
            { id: "mar", emoji: "🌊", name: "mar (바다)", rarity: "common", desc: "넓고 깊어요." },
            { id: "desierto", emoji: "🏜️", name: "desierto (사막)", rarity: "common", desc: "뜨겁고 건조해요." },
            { id: "bosque", emoji: "🌳", name: "bosque (숲)", rarity: "common", desc: "나무가 가득해요." },
            { id: "isla", emoji: "🏝️", name: "isla (섬)", rarity: "common", desc: "바다에 둘러싸였어요." },
            { id: "cueva", emoji: "🕳️", name: "cueva (동굴)", rarity: "common", desc: "어둡고 신비로워요." },
            { id: "campo", emoji: "🌾", name: "campo (들판)", rarity: "common", desc: "곡식이 자라요." },
            { id: "jardin", emoji: "🌷", name: "jardín (정원)", rarity: "common", desc: "꽃이 피어나요." },
            { id: "fuente", emoji: "⛲", name: "fuente (분수)", rarity: "common", desc: "시원하게 물을 뿜어요." },
            { id: "mercado", emoji: "🧺", name: "mercado (시장)", rarity: "common", desc: "활기가 넘쳐요." },
            { id: "cocina", emoji: "🍳", name: "cocina (부엌)", rarity: "common", desc: "맛있는 냄새가 나요." },
            { id: "plato", emoji: "🍽️", name: "plato (접시)", rarity: "common", desc: "음식을 담아요." },
            { id: "taza", emoji: "🍵", name: "taza (컵)", rarity: "common", desc: "따뜻한 걸 마셔요." },
            { id: "cuchara", emoji: "🥄", name: "cuchara (숟가락)", rarity: "common", desc: "떠먹어요." },
            { id: "cuchillo", emoji: "🔪", name: "cuchillo (칼)", rarity: "common", desc: "조심히 다뤄요." },
            { id: "botella", emoji: "🍾", name: "botella (병)", rarity: "common", desc: "축하할 때 열어요." },
            { id: "vaso", emoji: "🥤", name: "vaso (잔)", rarity: "common", desc: "시원하게 한 잔!" },
            { id: "nevera", emoji: "🧊", name: "nevera (냉장고)", rarity: "common", desc: "신선하게 보관해요." },
            { id: "horno", emoji: "🔥", name: "horno (오븐)", rarity: "common", desc: "맛있게 구워요." },
            { id: "torero", emoji: "🐂", name: "torero (투우사)", rarity: "rare", desc: "용감하게 맞서요." },
            { id: "gitano", emoji: "🎻", name: "gitano (집시)", rarity: "rare", desc: "자유로운 영혼이에요." },
            { id: "pirata", emoji: "🏴‍☠️", name: "pirata (해적)", rarity: "rare", desc: "보물을 찾아 떠나요." },
            { id: "caballero", emoji: "🛡️", name: "caballero (기사)", rarity: "rare", desc: "명예를 지켜요." },
            { id: "reina", emoji: "👸", name: "reina (여왕)", rarity: "rare", desc: "우아하고 강해요." },
            { id: "rey_r", emoji: "🤴", name: "rey (왕)", rarity: "rare", desc: "나라를 다스려요." },
            { id: "bruja", emoji: "🧙‍♀️", name: "bruja (마녀)", rarity: "rare", desc: "묘약을 만들어요." },
            { id: "monje", emoji: "🧘", name: "monje (수도사)", rarity: "rare", desc: "고요히 수행해요." },
            { id: "poeta", emoji: "📝", name: "poeta (시인)", rarity: "rare", desc: "말로 그림을 그려요." },
            { id: "pintor", emoji: "🖌️", name: "pintor (화가)", rarity: "rare", desc: "색으로 이야기해요." },
            { id: "bailarina", emoji: "🩰", name: "bailarina (무용수)", rarity: "rare", desc: "우아하게 움직여요." },
            { id: "cantante", emoji: "🎙️", name: "cantante (가수)", rarity: "rare", desc: "마음을 노래해요." },
            { id: "marinero", emoji: "⚓", name: "marinero (선원)", rarity: "rare", desc: "바다를 누벼요." },
            { id: "astronauta", emoji: "👨‍🚀", name: "astronauta (우주비행사)", rarity: "rare", desc: "별을 향해 가요." },
            { id: "detective", emoji: "🕵️", name: "detective (탐정)", rarity: "rare", desc: "단서를 찾아요." },
            { id: "cocinero", emoji: "👨‍🍳", name: "cocinero (요리사)", rarity: "rare", desc: "맛을 창조해요." },
            { id: "medico", emoji: "👨‍⚕️", name: "médico (의사)", rarity: "rare", desc: "생명을 구해요." },
            { id: "maestro", emoji: "👨‍🏫", name: "maestro (선생님)", rarity: "rare", desc: "지식을 나눠요." },
            { id: "catedral_s", emoji: "⛪", name: "Sagrada Familia (사그라다 파밀리아)", rarity: "rare", desc: "가우디의 걸작이에요!" },
            { id: "alhambra", emoji: "🕌", name: "Alhambra (알람브라)", rarity: "rare", desc: "무어인의 궁전이에요." },
            { id: "prado", emoji: "🖼️", name: "Museo del Prado (프라도 미술관)", rarity: "rare", desc: "명화가 가득해요." },
            { id: "camino", emoji: "🥾", name: "Camino de Santiago (산티아고 순례길)", rarity: "rare", desc: "걸어서 떠나요." },
            { id: "tomatina", emoji: "🍅", name: "La Tomatina (토마토 축제)", rarity: "rare", desc: "온통 토마토 범벅!" },
            { id: "sanfermin", emoji: "🐂", name: "San Fermín (소몰이 축제)", rarity: "rare", desc: "황소가 달려요!" },
            { id: "siesta", emoji: "😴", name: "siesta (낮잠)", rarity: "rare", desc: "스페인의 문화예요." },
            { id: "sobremesa", emoji: "☕", name: "sobremesa (식후 담소)", rarity: "rare", desc: "밥 먹고 나누는 대화." },
            { id: "duende_f", emoji: "✨", name: "duende (두엔데)", rarity: "rare", desc: "플라멩코의 영혼이에요." },
            { id: "olé", emoji: "👏", name: "olé (올레)", rarity: "rare", desc: "감탄의 외침!" },
            { id: "guitarra_f", emoji: "🎸", name: "guitarra flamenca (플라멩코 기타)", rarity: "rare", desc: "정열이 흘러요." },
            { id: "zapateado", emoji: "👞", name: "zapateado (발구르기)", rarity: "rare", desc: "바닥을 두드려요." },
            { id: "toro_bravo", emoji: "🐃", name: "toro bravo (투우소)", rarity: "rare", desc: "용맹함의 상징이에요." },
            { id: "mantilla", emoji: "🕸️", name: "mantilla (만틸랴)", rarity: "rare", desc: "전통 레이스 베일." },
            { id: "azulejo", emoji: "🔷", name: "azulejo (아술레호)", rarity: "rare", desc: "푸른 타일 장식이에요." },
            { id: "patio", emoji: "🏡", name: "patio (안뜰)", rarity: "rare", desc: "꽃으로 가득해요." },
            { id: "plaza", emoji: "🏛️", name: "plaza (광장)", rarity: "rare", desc: "사람들이 모여요." },
            { id: "tuna_m", emoji: "🎺", name: "tuna (투나)", rarity: "rare", desc: "대학생 악단이에요." },
            { id: "zarzuela", emoji: "🎭", name: "zarzuela (사르수엘라)", rarity: "rare", desc: "스페인식 오페라예요." },
            { id: "copla", emoji: "🎶", name: "copla (코플라)", rarity: "rare", desc: "전통 민요예요." },
            { id: "quijote", emoji: "🗡️", name: "Don Quijote (돈키호테)", rarity: "rare", desc: "풍차와 싸웠어요!" },
            { id: "sancho", emoji: "🫏", name: "Sancho Panza (산초 판사)", rarity: "rare", desc: "충직한 종자예요." },
            { id: "dali", emoji: "🎨", name: "Dalí (달리)", rarity: "rare", desc: "녹아내리는 시계!" },
            { id: "picasso", emoji: "🖼️", name: "Picasso (피카소)", rarity: "rare", desc: "형태를 해체했어요." },
            { id: "gaudi", emoji: "🏛️", name: "Gaudí (가우디)", rarity: "rare", desc: "곡선의 마법사예요." },
            { id: "goya", emoji: "🌑", name: "Goya (고야)", rarity: "rare", desc: "빛과 어둠의 화가." },
            { id: "cervantes", emoji: "📚", name: "Cervantes (세르반테스)", rarity: "rare", desc: "돈키호테를 썼어요." },
            { id: "lorca", emoji: "📜", name: "Lorca (로르카)", rarity: "rare", desc: "시로 노래했어요." },
            { id: "eldorado", emoji: "🏆", name: "El Dorado (엘도라도)", rarity: "epic", desc: "황금의 도시예요!" },
            { id: "atlantida", emoji: "🌊", name: "Atlántida (아틀란티스)", rarity: "epic", desc: "바다에 잠긴 문명." },
            { id: "fenix_e", emoji: "🔥", name: "ave fénix (불사조)", rarity: "epic", desc: "재에서 다시 태어나요." },
            { id: "ouroboros", emoji: "🐍", name: "uróboros (우로보로스)", rarity: "epic", desc: "자기 꼬리를 물어요." },
            { id: "yeti", emoji: "❄️", name: "yeti (예티)", rarity: "epic", desc: "설산의 그림자." },
            { id: "chupacabra", emoji: "🦇", name: "chupacabras (추파카브라)", rarity: "epic", desc: "라틴의 미스터리!" },
            { id: "kappa", emoji: "💧", name: "kappa (캇파)", rarity: "epic", desc: "물가의 요괴예요." },
            { id: "wendigo", emoji: "🌲", name: "wéndigo (웬디고)", rarity: "epic", desc: "숲의 굶주린 존재." },
            { id: "succubus", emoji: "😈", name: "íncubo (인큐버스)", rarity: "epic", desc: "꿈속에 나타나요." },
            { id: "valkyrie", emoji: "⚔️", name: "valquiria (발키리)", rarity: "epic", desc: "전사를 이끌어요." },
            { id: "nymph", emoji: "🌸", name: "ninfa (님프)", rarity: "epic", desc: "자연의 정령이에요." },
            { id: "siren_e", emoji: "🎶", name: "sirena cantante (세이렌)", rarity: "epic", desc: "노래로 유혹해요." },
            { id: "golem_i", emoji: "🧊", name: "gólem de hielo (얼음 골렘)", rarity: "epic", desc: "차가운 수호자." },
            { id: "elemental", emoji: "🌪️", name: "elemental (정령)", rarity: "epic", desc: "자연의 힘 그 자체." },
            { id: "archangel", emoji: "😇", name: "arcángel (대천사)", rarity: "epic", desc: "빛의 전령이에요." },
            { id: "demonio", emoji: "👿", name: "demonio (악마)", rarity: "epic", desc: "유혹의 속삭임." },
            { id: "dragon_h", emoji: "🧊", name: "dragón de hielo (얼음 용)", rarity: "epic", desc: "숨결이 얼려요." },
            { id: "dragon_s", emoji: "🌑", name: "dragón de sombra (그림자 용)", rarity: "epic", desc: "어둠에 숨어요." },
            { id: "kirin", emoji: "🦄", name: "kirin (기린수)", rarity: "epic", desc: "상서로운 짐승이에요." },
            { id: "roc", emoji: "🦅", name: "roc (로크)", rarity: "epic", desc: "코끼리도 낚아채요." },
            { id: "cyclops", emoji: "👁️", name: "cíclope (키클롭스)", rarity: "epic", desc: "눈이 하나예요." },
            { id: "harpy", emoji: "🪶", name: "arpía (하피)", rarity: "epic", desc: "날카롭게 울부짖어요." },
            { id: "medusa_e", emoji: "🐍", name: "Medusa (메두사)", rarity: "epic", desc: "머리카락이 뱀이에요." },
            { id: "chronos", emoji: "⏳", name: "Cronos (크로노스)", rarity: "epic", desc: "시간의 신이에요." },
            { id: "gaia", emoji: "🌍", name: "Gaia (가이아)", rarity: "epic", desc: "대지의 어머니." },
            { id: "poseidon", emoji: "🔱", name: "Poseidón (포세이돈)", rarity: "epic", desc: "바다를 다스려요." },
            { id: "hades", emoji: "💀", name: "Hades (하데스)", rarity: "epic", desc: "저승의 왕이에요." },
            { id: "prometheus", emoji: "🔥", name: "Prometeo (프로메테우스)", rarity: "epic", desc: "불을 훔쳐줬어요." },
            { id: "icarus", emoji: "🪽", name: "Ícaro (이카로스)", rarity: "epic", desc: "태양에 너무 가까이 갔어요." },
            { id: "pandora", emoji: "📦", name: "Pandora (판도라)", rarity: "epic", desc: "상자를 열었어요." },
            { id: "excalibur", emoji: "🗡️", name: "Excálibur (엑스칼리버)", rarity: "epic", desc: "선택받은 자의 검." },
            { id: "grial", emoji: "🏆", name: "Santo Grial (성배)", rarity: "epic", desc: "영원한 탐색의 대상." },
            { id: "aleph", emoji: "🔯", name: "alef (알레프)", rarity: "epic", desc: "모든 것을 담은 한 점." },
            { id: "axis", emoji: "🌐", name: "eje del mundo (세계축)", rarity: "epic", desc: "우주의 중심이에요." },
            { id: "hispanidad", emoji: "🌎", name: "hispanidad (히스파니다드)", rarity: "legendary", desc: "스페인어권 전체예요!" },
            { id: "rae", emoji: "📕", name: "la RAE (왕립학술원)", rarity: "legendary", desc: "스페인어를 지켜요." },
            { id: "subjuntivo", emoji: "🌀", name: "el subjuntivo (접속법)", rarity: "legendary", desc: "최종 보스예요!" },
            { id: "ser_estar", emoji: "⚖️", name: "ser y estar (세르와 에스타르)", rarity: "legendary", desc: "영원한 난제!" },
            { id: "fluidez", emoji: "🗣️", name: "fluidez (유창함)", rarity: "legendary", desc: "꿈에 그리던 경지!" },
            { id: "polyglot", emoji: "🌐", name: "políglota (다중언어자)", rarity: "legendary", desc: "여러 언어를 자유롭게!" },
            { id: "maestria", emoji: "🎓", name: "maestría (마스터)", rarity: "legendary", desc: "드디어 정복했어요!" },
            { id: "eterno", emoji: "♾️", name: "el eterno (영원한 자)", rarity: "legendary", desc: "끝없이 배워요." },
            { id: "nyanya_lab", emoji: "🔬", name: "nyanya-lab (냐냐 연구소)", rarity: "legendary", desc: "이 앱이 태어난 곳이에요!" },
            { id: "el_final", emoji: "🏁", name: "el final (마지막)", rarity: "legendary", desc: "도감의 끝에 도달했어요! 축하해요 🎉" },
        ];
